# Generated by Django 3.0.5 on 2020-05-08 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200508_1022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='favorite_product',
        ),
    ]
